server:
  port: :8080
techdata_dev:
  client_id: 
  client_secret: 
  oauthurl: https://eauth-quality.techdata.eu/as/token.oauth2
  soin: 
  signature: 
  timestamp: 
  token: 
techdata_live:
  client_id: 
  client_secret: 
  oauthurl: https://eauth.techdata.eu/as/token.oauth2
  signature: 
  soin: 
  timestamp: 
  token: 
